### ISSUE TITLE
Single-ROI visualisation in dashboard - ROI list not appearing

### ISSUE THREAD

**Issue by chrytsi** [neuroinformatics-unit/rsp-vision#89]
**Describe the bug**
The list of ROIs to choose from in the Single-ROI visualisation of the Dashboard is currently not appearing for any of the analysed experiments.
Ten days ago this list of ROIs would only appear once the facet plot for the default displayed ROI was loaded by clicking the "Show facet plot" button.

![ROI list missing](https://github.com/neuroinformatics-unit/rsp-vision/assets/34349487/6c3f0ccf-7589-4354-927c-5874c1d1424d)

**Computer used (please complete the following information):**

- OS: Windows 10

**Comment by lauraporta** [comment]
This is due to a change in the underlying data given new analysis features. Refer to the updated dashboard in the branch `penk-vs-non-penk`
