### ISSUE TITLE
ROI numbers between "Murakami plot" and "Single-ROI visualisation" in dashboard are off by 1

### ISSUE THREAD

**Issue by chrytsi** [neuroinformatics-unit/rsp-vision#92]
The ROI numbers between the "Murakami plot" and "Single-ROI visualisation" sections of the dashboard are off by 1.
This seems to be an issue of which ROIs are indicated to be responsive in the ROI list of the "Single-ROI visualisation" section. They are shifted by 1.
For example in experiment CX_142_3_hL_RSPd_monitor_front:
ROIs 4, 5, 6, 7 in Murakami plot become ROIs 3, 4, 5, 6 in Single-ROI visualisation but ROI 3 doesn't seem to be responsive _and_ it is only present on day 1 of the experiment.

**Comment by lauraporta** [comment]
Fixed in commit [29b0817](https://github.com/neuroinformatics-unit/rsp-vision/commit/29b081795a94250832f583706e1cd958f1a5868f)
